language: python
python:
  - "2.6"
  - "2.7"
env:
  - ERP=5 OORQ_DATABASE=oerp5 OORQ_DB_USER=postgres OORQ_DB_HOST=localhost
services:
  - redis-server
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - pip install -q -r tests/tests_${ERP}_requirements.txt
  - mkdir -p $VIRTUAL_ENV/src
  - pushd $VIRTUAL_ENV/src
  - curl -L https://github.com/akretion/openerp-server/archive/${ERP}.0.tar.gz | tar xvzf -
  - cd $VIRTUAL_ENV/src/openerp-server-${ERP}.0
  - python setup.py install
  - psql -c "create database $OORQ_DATABASE;" -U postgres
  - openerp-server --database=$OORQ_DATABASE --db_host=$OORQ_DB_HOST --db_user=$OORQ_DB_USER --init=all --stop-after-init
script:
  - popd
  - python -m unittest discover
notifications:
  irc: "irc.freenode.org#gisce-commits"
